### ISSUE TITLE
`.formula_list_to_named_list()` updates

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#121]
> discuss the opportunity of simplifying the syntax in `.formula_list_to_named_list()`, i.e. allowing to write `~ something` as a shortcut of `everything() ~ something`? @larmarange 

I"ve been thinking about updates to the syntax here as well. I like your suggestion. I would also like to accept a mix of formula and named element notation. For example, it would be helpful to be able to pass something like `statistic = list(all_categorical() ~ "{n}", age = "{mean}")`

**Comment by ddsjoberg** [comment]
@larmarange I am aiming for a gtsummary release in mid-October. After I make this update, do you want to make a broom.helpers release ahead of the gtsummary release?

**Comment by larmarange** [comment]
Dear @ddsjoberg   I have merged your PR and I will prepare a new release of broom.helpers, cf. https://github.com/larmarange/broom.helpers/issues/123

A quick question about GitHub Actions. I have seen that you deactivated GitHub actions for historic versions of R. Should we keep tests for R 3.4, 3.5 and 3.6 in broom.helpers?

**Comment by ddsjoberg** [comment]
> A quick question about GitHub Actions. I have seen that you deactivated GitHub actions for historic versions of R. Should we keep tests for R 3.4, 3.5 and 3.6 in broom.helpers?
@larmarange 

For some reason, all my Linux builds began failing a few weeks ago. I tried fixing them, but I couldn't figure it out uuuughhhhh My Department is having a small hackathon Thurs and Fri and they'll be some more novice programmers submitting pull requests. I deleted the GH Actions routines for now as to not confuse them.  I still need to figure it out (it's torture!)

**Comment by larmarange** [comment]
For your information, I have seen that haven is also updating their GitHub
actions : https://github.com/tidyverse/haven/pull/644

**Comment by ddsjoberg** [comment]
ahhhh! that's why they started to fail!

In that PR they are using the updated actions. But, the problem for us is that they now use {pak} to query, install, and cache the packages. When we run it on an old version of R that doesn't have all the Suggested package available, it now errors instead of skipping the installation.

**Comment by gorcha** [comment]
Hey all!

The prompt for updating the actions in haven is that GitHub have [deprecated the Ubuntu 16.04 runners](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/) as of last week, so we were seeing a similar problem (i.e. the Ubuntu CI jobs were never actually starting). I missed that blog post entirely and had the same "gah what the hell is it doing!" experience at first :stuck_out_tongue: 

I just updated to the newest version of the r-lib workflow templates because it was convenient, but if they're causing issues for you you should be able to use the same actions workflow file you've been using and just update the os from ubuntu-16.04 to ubuntu-18.04.

Hope that helps!

**Comment by ddsjoberg** [comment]
Thanks @gorcha ! I think updating the ubuntu machine only (not adopting the full update with pak) will be the way for us to go!

**Comment by larmarange** [comment]
Thanks @gorcha

**Comment by larmarange** [comment]
Dear @ddsjoberg   should we update the documentation of `.formula_list_to_named_list()`?

**Comment by ddsjoberg** [comment]
good idea, i'll update now
