### ISSUE TITLE
Note: 'switch' no alternative at select_utilities.R:106 

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#194]
I have that note when building broom.helpers.

https://github.com/larmarange/broom.helpers/blob/101605e3e459eb234c5d12bb45e13c744718ccf1/R/select_utilities.R#L108

@ddsjoberg could you have a look at it? please

**Comment by ddsjoberg** [comment]
@larmarange thanks for letting me know. much of this code can be simplified due to updates in tidyselect (when this was originally written i was using functions like `select_()` and friends).

I know you're planning a release by the end of the month. Do you mind if I update this for the next release? The next 3 weeks are super busy

**Comment by larmarange** [comment]
No problem. Don't woryy.
