### ISSUE TITLE
Warning about lengths not being a multiples of one another

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#268]
Hey! I noticed this warning pop up. If you don't have the badnwidth, I can investigate in the next couple of weeks

``` r
survival::coxph(survival::Surv(ttdeath, death) ~ age, id = response, data = gtsummary::trial) |> 
  broom.helpers::tidy_plus_plus()
#> Warning in tcm * w/n_obs_per_ind: longer object length is not a multiple of
#> shorter object length
#> Warning in w/n_obs_per_ind: longer object length is not a multiple of shorter
#> object length
#> # A tibble: 1 × 21
#>   term  variable var_label var_class var_type   var_nlevels contrasts
#>   <chr> <chr>    <chr>     <chr>     <chr>            <int> <chr>    
#> 1 age   age      Age       numeric   continuous          NA <NA>     
#> # ℹ 14 more variables: contrasts_type <chr>, reference_row <lgl>, label <chr>,
#> #   n_obs <dbl>, n_ind <dbl>, n_event <dbl>, exposure <dbl>, estimate <dbl>,
#> #   std.error <dbl>, robust.se <dbl>, statistic <dbl>, p.value <dbl>,
#> #   conf.low <dbl>, conf.high <dbl>
```

<sup>Created on 2024-08-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
This is due to the fact that there are some missing values in **response** variable passed to `id`.

`model.frame()` properly remove these lines with missing values for the identifier but variable labels are lost in the process.
`model.frame.default()` keep the variable labels but does not take into account the `id`.

So far, `model_get_model_frame.coxph()` used `model.frame.default()` to keep the variable resulting in an error in this specific case.
I have updated the function to use instead `model.frame()`, copying then the variable labels from `model.frame.default()`.

**Comment by larmarange** [comment]
done here #269 

let me know if it looks ok for you
