### ISSUE TITLE
Add tidy_select_variables()

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#45]
This function will allow to keep only certain variables in the output.

Two arguments: keep and drop.

To be added also to tidy_plus_plus()

**Comment by ddsjoberg** [comment]
@larmarange this is great! What do you think of expanding it to use tidyselect?

I'd you're amenable, I can outline something and implement it in a PR?

**Comment by larmarange** [comment]
I am open

**Comment by larmarange** [comment]
I am open for adding tidyselect support. I'm not very familiar with it, but I'm open to it of course.

**Comment by ddsjoberg** [comment]
I think there will only be a couple of changes to the user experience after implementing tidyselect.

1. Since the tidyselect both selects and removes columns (e.g. `select(age)` and `select(-age)`), the selecting argument would be simplified into a single argument.

1. I think the current `strict=` argument would need to be removed. If a user needs to select variables that may or may not be present in the model, they would use the tidyselect function `any_of()`, e.g. `trial %>% select(any_of(c("age", "stage", "NOPE"))`.

**Comment by larmarange** [comment]
Right

**Comment by ddsjoberg** [comment]
Great, I"ll get started on it

**Comment by ddsjoberg** [comment]
Should I add tidyselect to the other functions?  Here's what I think it could be used...

- `tidy_plus_plus(show_single_row=)`
- `tidy_add_header_rows(show_single_row=)`
- `tidy_add_reference_rows(no_reference_row=)`

**Comment by larmarange** [comment]
Yes why not, with pleasure
