### ISSUE TITLE
Fix lmer Issue with Random Effects being Dropped

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#88]
The random effects rows returned by `tidy()` are being stripped away in `tidy_plus_plus()`. (See example in https://github.com/larmarange/broom.helpers/issues/87)

- [ ] Fix this issue
- [ ] Can we add a message somewhere if rows have been silently removed?

I can implement this in the next few weeks

**Comment by larmarange** [comment]
Technically, they are dropped only if `intercept = FALSE`.

The issue is with var_type as they are classified as "Intercept".  We need to identify such terms and to give them another "var_type" (what would be the appropriate type? 'random'?). Such terms are not managed by `model_identify_variables()`

2 possible options:

- in `tidy_indentify_variable`: identify such terms by detecting the string "sd__" at the beginning of terms names
- identify them in the appropriate method in `model_identify_variables()`

``` r
library(broom.helpers)


fit <- lme4::lmer(age ~ grade + (1|stage), gtsummary::trial) 
#> boundary (singular) fit: see ?isSingular

fit %>% tidy_plus_plus(intercept = TRUE) %>% knitr::kable()
#> Registered S3 method overwritten by 'broom.mixed':
#>   method      from 
#>   tidy.gamlss broom
```

<table style="width:100%;">
<colgroup>
<col style="width: 7%" />
<col style="width: 7%" />
<col style="width: 7%" />
<col style="width: 4%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 7%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 7%" />
<col style="width: 2%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 5%" />
<col style="width: 4%" />
<col style="width: 4%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: left;">variable</th>
<th style="text-align: left;">var_label</th>
<th style="text-align: left;">var_class</th>
<th style="text-align: left;">var_type</th>
<th style="text-align: right;">var_nlevels</th>
<th style="text-align: left;">contrasts</th>
<th style="text-align: left;">contrasts_type</th>
<th style="text-align: left;">reference_row</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n_obs</th>
<th style="text-align: left;">effect</th>
<th style="text-align: left;">group</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">189</td>
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">46.151515</td>
<td style="text-align: right;">1.768127</td>
<td style="text-align: right;">26.1019271</td>
<td style="text-align: right;">42.686050</td>
<td style="text-align: right;">49.616980</td>
</tr>
<tr class="even">
<td style="text-align: left;">gradeI</td>
<td style="text-align: left;">grade</td>
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">treatment</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">I</td>
<td style="text-align: right;">66</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gradeII</td>
<td style="text-align: left;">grade</td>
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">treatment</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">II</td>
<td style="text-align: right;">62</td>
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1.380743</td>
<td style="text-align: right;">2.540519</td>
<td style="text-align: right;">0.5434884</td>
<td style="text-align: right;">-3.598584</td>
<td style="text-align: right;">6.360070</td>
</tr>
<tr class="even">
<td style="text-align: left;">gradeIII</td>
<td style="text-align: left;">grade</td>
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">treatment</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">III</td>
<td style="text-align: right;">61</td>
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1.963239</td>
<td style="text-align: right;">2.551234</td>
<td style="text-align: right;">0.7695252</td>
<td style="text-align: right;">-3.037088</td>
<td style="text-align: right;">6.963566</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">stage</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">Residual</td>
<td style="text-align: right;">14.364330</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
Or we can check if there is an **effect** column in the table returned by the tidy function. If such column exists and if the value is equal to "ran_pars", then change **var_type** to "ran_pars". 

As such terms will not be considered as intercepts anymore, they will not be stripped by default by `tidy_plus_plus()`

**Comment by larmarange** [comment]
Additional question:

for random parameters, should the value of **group** be used for the **variable** columns?

**Comment by larmarange** [comment]
@ddsjoberg Please have a look at PR #88

``` r
library(broom.helpers)


fit <- lme4::lmer(age ~ grade + (1|stage), gtsummary::trial) 
#> boundary (singular) fit: see ?isSingular

fit %>% tidy_plus_plus(intercept) %>% knitr::kable()
#> Registered S3 method overwritten by 'broom.mixed':
#>   method      from 
#>   tidy.gamlss broom
#> Warning in dplyr::as_tibble(.): redémarrage de l'évaluation d'une promesse
#> interrompue

#> Warning in dplyr::as_tibble(.): redémarrage de l'évaluation d'une promesse
#> interrompue
#> x There was an error calling `tidy_fun()`. Most likely, this is because
#>   the function supplied in `tidy_fun=` was misspelled, does not exist,
#>   is not compatible with your object, or was missing necessary arguments (e.g.
#>   `conf.level=` or `conf.int=`). See error message below.
#> Error: Error in dplyr::as_tibble(.): objet 'intercept' introuvable

fit %>% tidy_plus_plus(intercept = TRUE) %>% knitr::kable()
```

<table>
<colgroup>
<col style="width: 7%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 4%" />
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 7%" />
<col style="width: 7%" />
<col style="width: 6%" />
<col style="width: 7%" />
<col style="width: 2%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 5%" />
<col style="width: 4%" />
<col style="width: 4%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: left;">variable</th>
<th style="text-align: left;">var_label</th>
<th style="text-align: left;">var_class</th>
<th style="text-align: left;">var_type</th>
<th style="text-align: right;">var_nlevels</th>
<th style="text-align: left;">contrasts</th>
<th style="text-align: left;">contrasts_type</th>
<th style="text-align: left;">reference_row</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n_obs</th>
<th style="text-align: left;">effect</th>
<th style="text-align: left;">group</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">189</td>
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">46.151515</td>
<td style="text-align: right;">1.768127</td>
<td style="text-align: right;">26.1019271</td>
<td style="text-align: right;">42.686050</td>
<td style="text-align: right;">49.616980</td>
</tr>
<tr class="even">
<td style="text-align: left;">gradeI</td>
<td style="text-align: left;">grade</td>
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">treatment</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">I</td>
<td style="text-align: right;">66</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gradeII</td>
<td style="text-align: left;">grade</td>
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">treatment</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">II</td>
<td style="text-align: right;">62</td>
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1.380743</td>
<td style="text-align: right;">2.540519</td>
<td style="text-align: right;">0.5434884</td>
<td style="text-align: right;">-3.598584</td>
<td style="text-align: right;">6.360070</td>
</tr>
<tr class="even">
<td style="text-align: left;">gradeIII</td>
<td style="text-align: left;">grade</td>
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">treatment</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">III</td>
<td style="text-align: right;">61</td>
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1.963239</td>
<td style="text-align: right;">2.551234</td>
<td style="text-align: right;">0.7695252</td>
<td style="text-align: right;">-3.037088</td>
<td style="text-align: right;">6.963566</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: left;">stage</td>
<td style="text-align: left;">T Stage</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">ran_pars</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">stage</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: left;">Residual</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">ran_pars</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">Residual</td>
<td style="text-align: right;">14.364330</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
